// Ties the OPFS helpers (opfs.ts) together with the wasm bridge's collection
// lifecycle: on first launch there's nothing in OPFS yet, so we bootstrap
// from a bundled starter fixture (one real note/card, generated by
// rust/tools/make-test-collection — see web/scripts/sync-wasm-artifacts.sh);
// on every later launch, OPFS has the collection as it was last left.

import {
  opfsFileExists,
  readOpfsFile,
  writeOpfsFile,
  writeOpfsMediaFile,
  readOpfsMediaFile,
  listOpfsMediaFiles,
  deleteOpfsMediaFile,
} from './opfs'
import {
  initBackend,
  openCollection,
  readCollectionBytes,
  listMediaFiles,
  readMediaFile,
  writeMediaFile,
  readMediaDbBytes,
  writeMediaDbBytes,
  deleteUnusedMedia,
} from '../wasm/backend'

/** Filename the collection is persisted under at the root of OPFS. */
const COLLECTION_OPFS_FILENAME = 'collection.anki2'

/** Filename the media sync tracking database is persisted under at the root
 * of OPFS — a completely separate database from the collection itself (see
 * `readMediaDbBytes` in wasm/backend.ts). */
const MEDIA_DB_OPFS_FILENAME = 'collection.mdb'

/** Bundled fixture used to seed OPFS on first launch (before any real
 * collection has been synced/imported). Served from public/wasm/ — see
 * web/scripts/sync-wasm-artifacts.sh. */
const STARTER_COLLECTION_URL = '/wasm/starter-collection.anki2'

/**
 * Returns the bytes to feed into `openCollection`: whatever is already
 * persisted in OPFS, or (on first launch) the bundled starter fixture.
 * Does NOT write to OPFS itself — call `persistCollection` after a
 * successful `openCollection` so the starter fixture's *opened* state (which
 * may differ subtly from the on-disk bytes once rslib touches it) is what
 * ends up persisted, not the raw fixture bytes.
 */
export async function loadInitialCollectionBytes(): Promise<Uint8Array> {
  if (await opfsFileExists(COLLECTION_OPFS_FILENAME)) {
    return readOpfsFile(COLLECTION_OPFS_FILENAME)
  }

  const response = await fetch(STARTER_COLLECTION_URL)
  if (!response.ok) {
    throw new Error(
      `failed to fetch starter collection fixture (${response.status} ${response.statusText}) ` +
        `from ${STARTER_COLLECTION_URL} — did you run web/scripts/sync-wasm-artifacts.sh?`,
    )
  }
  return new Uint8Array(await response.arrayBuffer())
}

/**
 * Persists the collection's current bytes (read back out of the wasm
 * bridge's virtual FS) to OPFS. Call this after `openCollection` succeeds and
 * after every mutating call (`answerCard`) — nothing survives a reload
 * otherwise, since the bridge only ever writes to Emscripten's in-memory FS.
 */
export async function persistCollection(): Promise<void> {
  const bytes = await readCollectionBytes()
  await writeOpfsFile(COLLECTION_OPFS_FILENAME, bytes)
}

/**
 * Copies every media file the backend currently has (written into Emscripten's
 * in-memory FS by `import_apkg`) out to OPFS, so audio/images survive a reload.
 * Call this after a successful `importApkg` + `persistCollection`.
 *
 * Returns the number of files persisted (for logging/telemetry). Files already
 * in OPFS are simply overwritten — importing a deck that shares media with an
 * existing one is therefore idempotent, not a conflict.
 */
export async function persistMedia(): Promise<number> {
  const names = await listMediaFiles()
  for (const name of names) {
    const bytes = await readMediaFile(name)
    await writeOpfsMediaFile(name, bytes)
  }
  return names.length
}

/**
 * Restores every media file persisted in OPFS back into the backend's
 * in-memory FS. Card *rendering* does not need this (it only emits filenames;
 * display reads media straight from OPFS — see web/src/wasm/media.ts), so this
 * is NOT part of the mandatory bootstrap: it exists for rslib operations that
 * actually read media bytes (re-export, media check) and is deliberately kept
 * off the first-load hot path because eagerly rehydrating thousands of files
 * (e.g. Ankizin's ~5.6k) into wasm memory would stall the first render for no
 * display benefit. See docs/ARCHITECTURE.md §13 for the measured cost.
 *
 * Returns the number of files restored.
 */
export async function restoreMediaToBackend(): Promise<number> {
  const names = await listOpfsMediaFiles()
  for (const name of names) {
    const bytes = await readOpfsMediaFile(name)
    if (bytes) await writeMediaFile(name, bytes)
  }
  return names.length
}

/**
 * Persists the media *sync tracking database*'s current bytes to OPFS — a
 * completely separate database from the collection and from the media files
 * themselves (see `readMediaDbBytes`'s doc comment in wasm/backend.ts). Call
 * after any operation that touches it (`syncMedia`, `importApkg`); without
 * this, `last_sync_usn` and every file's last-known checksum are lost on
 * reload, forcing the next media sync to reconcile the entire library
 * against the server from scratch instead of just what's actually changed.
 *
 * A `null` result (nothing to persist yet — no media sync/import has run
 * this collection's lifetime) is a normal no-op, not an error.
 */
export async function persistMediaDb(): Promise<void> {
  const bytes = await readMediaDbBytes()
  if (bytes) await writeOpfsFile(MEDIA_DB_OPFS_FILENAME, bytes)
}

/**
 * Restores the media tracking database persisted by `persistMediaDb()` back
 * into the backend's virtual FS. Call once during collection bootstrap
 * (`ensureCollectionReady`, right after `openCollection`) — unlike
 * `restoreMediaToBackend` (the media *files*, deliberately NOT restored
 * eagerly since rehydrating thousands of files would stall the first
 * render), this is a single small file and cheap to restore unconditionally.
 * A first-ever launch (nothing persisted yet) is a normal no-op: the next
 * `col.media()` call creates a fresh database, exactly as it always has.
 */
export async function restoreMediaDbToBackend(): Promise<void> {
  if (await opfsFileExists(MEDIA_DB_OPFS_FILENAME)) {
    const bytes = await readOpfsFile(MEDIA_DB_OPFS_FILENAME)
    await writeMediaDbBytes(bytes)
  }
}

/**
 * Deletes every unused (unreferenced) media file — the explicit second step of
 * Check Media — and keeps all three places media state lives consistent:
 *
 *  1. `deleteUnusedMedia()` (wasm) physically removes the files from the
 *     backend's media folder AND marks their media-DB entries
 *     `sha1: None, sync_required: true`.
 *  2. `deleteOpfsMediaFile()` removes each deleted file from OPFS, so the
 *     browser-side persistent copy doesn't linger (the card renderer reads
 *     media straight from OPFS — see web/src/wasm/media.ts).
 *  3. `persistMediaDb()` writes the updated media-DB (with those
 *     `sync_required` marks) back to OPFS. This is the load-bearing step:
 *     without it the marks are lost on reload and the deletion never
 *     propagates to the server on the next media sync — the same
 *     OPFS/media-DB consistency issue `persistMedia`/`persistMediaDb` were
 *     added to fix for media sync (see their doc comments above).
 *
 * Returns the number of files deleted.
 */
export async function checkAndDeleteUnusedMedia(): Promise<number> {
  const deletedNames = await deleteUnusedMedia()
  for (const name of deletedNames) {
    await deleteOpfsMediaFile(name)
  }
  await persistMediaDb()
  return deletedNames.length
}

// Shared bootstrap so any view (StudyView, the import/deck-picker UI) can
// safely assume the backend is initialised and a collection is open,
// regardless of which one happens to mount first — App.tsx mounts exactly
// one tab's view at a time, so either could be the first to run this.
// Memoized the same way backend.ts's own initBackend/openCollection are:
// later calls just await the same in-flight/completed bootstrap rather than
// redoing (OPFS reads, the starter-fixture fetch, opening the connection).
let ensureCollectionReadyPromise: Promise<void> | null = null

export async function ensureCollectionReady(): Promise<void> {
  if (ensureCollectionReadyPromise) return ensureCollectionReadyPromise

  ensureCollectionReadyPromise = (async () => {
    await initBackend()
    const bytes = await loadInitialCollectionBytes()
    await openCollection(bytes)
    // Restore any previously-persisted media tracking DB before anything
    // else can call `col.media()` (import, sync) and create a fresh, empty
    // one at the same path instead.
    await restoreMediaDbToBackend()
    // Persist right away: if this launch bootstrapped from the bundled
    // starter fixture, OPFS now has its own copy so future launches resume
    // from OPFS instead of re-seeding from the fixture.
    await persistCollection()
  })()

  return ensureCollectionReadyPromise
}
