// Ties the OPFS helpers (opfs.ts) together with the wasm bridge's collection
// lifecycle: on first launch there's nothing in OPFS yet, so we bootstrap
// from a bundled starter fixture (one real note/card, generated by
// rust/tools/make-test-collection — see web/scripts/sync-wasm-artifacts.sh);
// on every later launch, OPFS has the collection as it was last left.

import {
  opfsFileExists,
  readOpfsFile,
  writeOpfsFile,
  writeOpfsMediaFile,
  readOpfsMediaFile,
  listOpfsMediaFiles,
} from './opfs'
import {
  initBackend,
  openCollection,
  readCollectionBytes,
  listMediaFiles,
  readMediaFile,
  writeMediaFile,
} from '../wasm/backend'

/** Filename the collection is persisted under at the root of OPFS. */
const COLLECTION_OPFS_FILENAME = 'collection.anki2'

/** Bundled fixture used to seed OPFS on first launch (before any real
 * collection has been synced/imported). Served from public/wasm/ — see
 * web/scripts/sync-wasm-artifacts.sh. */
const STARTER_COLLECTION_URL = '/wasm/starter-collection.anki2'

/**
 * Returns the bytes to feed into `openCollection`: whatever is already
 * persisted in OPFS, or (on first launch) the bundled starter fixture.
 * Does NOT write to OPFS itself — call `persistCollection` after a
 * successful `openCollection` so the starter fixture's *opened* state (which
 * may differ subtly from the on-disk bytes once rslib touches it) is what
 * ends up persisted, not the raw fixture bytes.
 */
export async function loadInitialCollectionBytes(): Promise<Uint8Array> {
  if (await opfsFileExists(COLLECTION_OPFS_FILENAME)) {
    return readOpfsFile(COLLECTION_OPFS_FILENAME)
  }

  const response = await fetch(STARTER_COLLECTION_URL)
  if (!response.ok) {
    throw new Error(
      `failed to fetch starter collection fixture (${response.status} ${response.statusText}) ` +
        `from ${STARTER_COLLECTION_URL} — did you run web/scripts/sync-wasm-artifacts.sh?`,
    )
  }
  return new Uint8Array(await response.arrayBuffer())
}

/**
 * Persists the collection's current bytes (read back out of the wasm
 * bridge's virtual FS) to OPFS. Call this after `openCollection` succeeds and
 * after every mutating call (`answerCard`) — nothing survives a reload
 * otherwise, since the bridge only ever writes to Emscripten's in-memory FS.
 */
export async function persistCollection(): Promise<void> {
  const bytes = await readCollectionBytes()
  await writeOpfsFile(COLLECTION_OPFS_FILENAME, bytes)
}

/**
 * Copies every media file the backend currently has (written into Emscripten's
 * in-memory FS by `import_apkg`) out to OPFS, so audio/images survive a reload.
 * Call this after a successful `importApkg` + `persistCollection`.
 *
 * Returns the number of files persisted (for logging/telemetry). Files already
 * in OPFS are simply overwritten — importing a deck that shares media with an
 * existing one is therefore idempotent, not a conflict.
 */
export async function persistMedia(): Promise<number> {
  const names = await listMediaFiles()
  for (const name of names) {
    const bytes = await readMediaFile(name)
    await writeOpfsMediaFile(name, bytes)
  }
  return names.length
}

/**
 * Restores every media file persisted in OPFS back into the backend's
 * in-memory FS. Card *rendering* does not need this (it only emits filenames;
 * display reads media straight from OPFS — see web/src/wasm/media.ts), so this
 * is NOT part of the mandatory bootstrap: it exists for rslib operations that
 * actually read media bytes (re-export, media check) and is deliberately kept
 * off the first-load hot path because eagerly rehydrating thousands of files
 * (e.g. Ankizin's ~5.6k) into wasm memory would stall the first render for no
 * display benefit. See docs/ARCHITECTURE.md §13 for the measured cost.
 *
 * Returns the number of files restored.
 */
export async function restoreMediaToBackend(): Promise<number> {
  const names = await listOpfsMediaFiles()
  for (const name of names) {
    const bytes = await readOpfsMediaFile(name)
    if (bytes) await writeMediaFile(name, bytes)
  }
  return names.length
}

// Shared bootstrap so any view (StudyView, the import/deck-picker UI) can
// safely assume the backend is initialised and a collection is open,
// regardless of which one happens to mount first — App.tsx mounts exactly
// one tab's view at a time, so either could be the first to run this.
// Memoized the same way backend.ts's own initBackend/openCollection are:
// later calls just await the same in-flight/completed bootstrap rather than
// redoing (OPFS reads, the starter-fixture fetch, opening the connection).
let ensureCollectionReadyPromise: Promise<void> | null = null

export async function ensureCollectionReady(): Promise<void> {
  if (ensureCollectionReadyPromise) return ensureCollectionReadyPromise

  ensureCollectionReadyPromise = (async () => {
    await initBackend()
    const bytes = await loadInitialCollectionBytes()
    await openCollection(bytes)
    // Persist right away: if this launch bootstrapped from the bundled
    // starter fixture, OPFS now has its own copy so future launches resume
    // from OPFS instead of re-seeding from the fixture.
    await persistCollection()
  })()

  return ensureCollectionReadyPromise
}
